const config = {
  appName: 'chatops-knight',
  baseUrl: 'https://127.0.0.1:8200/v1',
  rootPath: 'secrets',
  timeout: 1000,
  proxy: false,
  createPath: 'data',
  updatePath: 'data',
  readPath: 'data',
  lvDeletePath: 'data',
  deletePath: 'delete',
  undeletePath: 'undelete',
  destroyPath: 'destroy',
  enginePath: 'config',
  listPath: 'metadata',
  appRoleLogin: '/auth/approle/login',
  appRolePath: '/auth/approle/role',
  sysHealth: '/sys/health',
  sysSealStatus: '/sys/seal-status',
  sysHostInfo: '/sys/host-info',
  sysCapabilities: '/sys/capabilities',
  sysCapabilitiesSelf: '/sys/capabilities-self',
  sysInternalCounters: '/sys/internal/counters',
  sysCounterTypes: [ "requests", "entities", "tokens" ],
  sysMetrics: '/sys/metrics',
  sysMetricFormats: [ "prometheus" ],
  sysSeal: '/sys/seal',
  sysUnseal: '/sys/unseal'
};

module.exports = config;
